export const projectsData = [
    {
        id: 1,
        src: "/images/projects/realitytiger.jpg",
        link: "https://www.realitytiger.com",
        category: "Design & Develop",
        title: "Reality Tiger",
        year: "2024",
        client: "Reality Tiger",
        services: "Web Design & Development",
        project: "Real Estate Portal",
        headerTitle: "Beautiful platform for Real Estate",
        desc1: "Reality Tiger required a comprehensive web platform to showcase premium real estate listings dynamically. We architected a complete digital experience focused on smooth property navigation, advanced search filtering, and user engagement, ensuring clients find their dream homes with zero friction.",
        desc2: "Our development emphasized performance and responsiveness across all devices, coupling a sleek, modern UI with a robust back-end capable of handling high-traffic volumes securely and efficiently.",
        desktopImg: "/images/projects/realitytiger_desktop.jpg",
        tabletImg: "/images/projects/realitytiger_tablet.jpg",
        mobileImg: "/images/projects/realitytiger_mobile.jpg",
        gallery: [
            "/images/projects/single-project1.jpg",
            "/images/projects/single-project2.jpg",
            "/images/projects/single-project3.jpg",
            "/images/projects/single-project4.jpg"
        ]
    },
    {
        id: 2,
        src: "/images/projects/ahyan.jpg",
        link: "https://ahyan.co.in/",
        category: "Design & Develop",
        title: "Ahyan",
        year: "2023",
        client: "Ahyan",
        services: "Web Design & Development",
        project: "Corporate Website",
        headerTitle: "Sleek corporate identity and web presence",
        desc1: "For Ahyan, we designed and developed an elegant corporate website from the ground up that firmly established their digital presence. The core objective was bridging their brand heritage with a forward-looking digital strategy to capture and convert enterprise clients.",
        desc2: "We delivered an intuitively structured architecture, complete with interactive elements, responsive breakpoints, and SEO optimization—setting Ahyan apart as an industry leader with a truly engaging user experience.",
        desktopImg: "/images/projects/ahyan_desktop.jpg",
        tabletImg: "/images/projects/ahyan_tablet.jpg",
        mobileImg: "/images/projects/ahyan_mobile.jpg",
        gallery: [
            "/images/projects/single-project1.jpg",
            "/images/projects/single-project2.jpg",
            "/images/projects/single-project3.jpg",
            "/images/projects/single-project4.jpg"
        ]
    },
    {
        id: 3,
        src: "/images/projects/bhaggyam.jpg",
        link: "https://www.bhaggyamconstructions.com/",
        category: "Design & Develop",
        title: "Bhaggyam Construction",
        year: "2023",
        client: "Bhaggyam",
        services: "Web Design & Development",
        project: "Construction Showcase",
        headerTitle: "A solid digital foundation for construction",
        desc1: "Bhaggyam Constructions needed a digital upgrade to match their massive real-world projects. We completely redesigned their online portfolio to visually highlight ongoing and completed structural developments, emphasizing precision, trust, and structural integrity.",
        desc2: "Through immersive layouts and high-performance asset delivery, we managed to convey the scale of their work digitally while maintaining insanely fast page load times and seamless navigation.",
        desktopImg: "/images/projects/bhaggyam_desktop.jpg",
        tabletImg: "/images/projects/bhaggyam_tablet.jpg",
        mobileImg: "/images/projects/bhaggyam_mobile.jpg",
        gallery: [
            "/images/projects/single-project1.jpg",
            "/images/projects/single-project2.jpg",
            "/images/projects/single-project3.jpg",
            "/images/projects/single-project4.jpg"
        ]
    },
    {
        id: 4,
        src: "/images/projects/wheelersedu.jpg",
        link: "https://www.wheelersedu.com/",
        category: "Design & Develop",
        title: "Wheelers Edu",
        year: "2024",
        client: "Wheelers Edu",
        services: "Web Design & Development",
        project: "Educational Consulting",
        headerTitle: "Empowering students through digital avenues",
        desc1: "Wheelers Edu assists students in finding incredible study-abroad opportunities. We designed a trustworthy, incredibly accessible website that organizes vast amounts of institutional data, visas, and program information into easily digestible funnels.",
        desc2: "The platform's frontend provides immediate clarity to prospective students, while the backend gives Wheelers Edu administrators absolute control over dynamic content, events, and consultation bookings.",
        desktopImg: "/images/projects/wheelersedu_desktop.jpg",
        tabletImg: "/images/projects/wheelersedu_tablet.jpg",
        mobileImg: "/images/projects/wheelersedu_mobile.jpg",
        gallery: [
            "/images/projects/single-project1.jpg",
            "/images/projects/single-project2.jpg",
            "/images/projects/single-project3.jpg",
            "/images/projects/single-project4.jpg"
        ]
    },
    {
        id: 5,
        src: "/images/projects/billiontags.jpg",
        link: "https://www.billiontags.com",
        category: "Develop",
        title: "Billion Tags",
        year: "2024",
        client: "Billion Tags",
        services: "Web Development",
        project: "E-Commerce",
        headerTitle: "High-yield e-commerce platform deployment",
        desc1: "Billion Tags arrived with intricate e-commerce requirements needing highly specialized development. We took charge of building a hyper-efficient frontend and a lightning-fast catalog capable of surfacing exactly what users want right away.",
        desc2: "Our development team implemented advanced state management, flawless payment gateway integrations, and strict security protocols resulting in drastically reduced cart abandonment and a deeply satisfying shopper experience.",
        desktopImg: "/images/projects/billiontags_desktop.jpg",
        tabletImg: "/images/projects/billiontags_tablet.jpg",
        mobileImg: "/images/projects/billiontags_mobile.jpg",
        gallery: [
            "/images/projects/single-project1.jpg",
            "/images/projects/single-project2.jpg",
            "/images/projects/single-project3.jpg",
            "/images/projects/single-project4.jpg"
        ]
    },
    {
        id: 6,
        src: "/images/projects/jandjp.jpg",
        link: "https://www.jandjp.in",
        category: "Handling",
        title: "J and J P",
        year: "2024",
        client: "J & J P",
        services: "Website Handling & Maintenance",
        project: "Managed Services",
        headerTitle: "Continuous digital maintenance and optimization",
        desc1: "Managing J and J P involves rigorous ongoing maintenance, critical updates, performance tuning, and content management. We operate as their dedicated digital arm, proactively securing infrastructure and resolving performance bottlenecks before they affect users.",
        desc2: "By overseeing all technical and operational facets of their website, we enable J and J P to focus entirely on their core business, safe in the knowledge that their digital performance sits in expert hands.",
        desktopImg: "/images/projects/jandjp_desktop.jpg",
        tabletImg: "/images/projects/jandjp_tablet.jpg",
        mobileImg: "/images/projects/jandjp_mobile.jpg",
        gallery: [
            "/images/projects/single-project1.jpg",
            "/images/projects/single-project2.jpg",
            "/images/projects/single-project3.jpg",
            "/images/projects/single-project4.jpg"
        ]
    }
]